funstore/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from store.views import (EntertainmentView, AddToBasketView, BasketView, DelFromBasketView, ConfirmView, PDFView,
    PaymentSuccessView, PaymentFailureView, PayUrlView, OrderItemsView)


urlpatterns = patterns(
    '',
    url(r'^$',                      EntertainmentView.as_view(),    name='home'),
    url(r'^add_to_basket$',         AddToBasketView.as_view(),      name='add_to_basket'),
    url(r'^del_from_basket$',       DelFromBasketView.as_view(),    name='del_from_basket'),
    url(r'^basket$',                BasketView.as_view(),           name='basket'),
    url(r'^pdf/(?P<code>[-_\w]+)$', PDFView.as_view(),              name='pdf'),
    url(r'^confirm$',               ConfirmView.as_view(),          name='confirm'),
    url(r'^payment_success$',       PaymentSuccessView.as_view(),   name='payment_success'),
    url(r'^payment_failure$',       PaymentFailureView.as_view(),   name='payment_failure'),
    url(r'^pay_url$',               PayUrlView.as_view(),           name='pay_url'),
    url(r'^order_items',            OrderItemsView.as_view(),       name='order_items'),
    url(r'^admin/', include(admin.site.urls)),
)

store/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from .models import Basket, BasketItem, Order, OrderItem, OrderExtraItem, BASKET_CLOSED


class BasketForm(ModelForm):
    class Meta:
        model = Basket
        fields = ['session_id',]


BasketItemFormSet = inlineformset_factory(Basket, BasketItem, extra=0)


class CardForm(forms.Form):
    login = forms.CharField(required=True, label=u'Логин карты')
    password = forms.CharField(required=True, label=u'Пароль карты', widget=forms.PasswordInput())


class OrderCreateForm(forms.Form):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=False)

    def save(self, request):
        cd = self.cleaned_data
        # try:
        basket = Basket.objects.get(id=request.session.get('basket_id'))
        # with transaction.atomic():
        order = Order(
            username=cd['username'],
            email=cd['email'],
            phone=cd['phone']
        )
        order.save()
        for basket_item in basket.items.all():
            for _ in range(basket_item.count):
                OrderItem.objects.create(
                    order=order,
                    name=basket_item.item.name,
                    price=basket_item.item.price,
                    revenue=basket_item.item.revenue,
                    conditions=basket_item.item.conditions,
                    explanations=basket_item.item.explanations,
                    peoples=basket_item.item.peoples,
                    duration=basket_item.item.duration,
                    date_expiration=basket_item.item.date_expiration,
                    partner=basket_item.item.partner,
                    type=basket_item.item.type
                )

        for extra_item in basket.extra_items.all():
            OrderExtraItem.objects.create(
                order=order,
                type=extra_item.type,
                name=extra_item.name,
                price=extra_item.price
            )

        for transaction in basket.transactions.all():
            transaction.order = order
            transaction.save()

        basket.status = BASKET_CLOSED
        basket.save()
        request.session['order_id'] = order.id

        return order

store/views.py
# -*- coding:utf-8 -*-
import datetime

from django import http
from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Sum
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import get_template
from django.template import Context
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, RedirectView, UpdateView, DeleteView, TemplateView, FormView
import xhtml2pdf.pisa as pisa

from .models import Entertainment, CategoryItem, CATEGORY_ONLY, Basket, Order, \
    BasketItem, BASKET_OPEN, ORDER_NEW, PRODUCT, BasketExtaItem, DELIVERY, SiteConfiguration, OrderItem, \
    ORDER_ITEM_PAYED, ORDER_PAYED, CARD, SERVICE, Card, TRANSACTION_ACCEPTED, CardTransaction, ORDER_ITEM_STATUS, \
    Partner
from .forms import BasketForm, BasketItemFormSet, OrderCreateForm, CardForm

try:
    import StringIO
    StringIO = StringIO.StringIO
except Exception:
    from io import StringIO

import cgi
import hashlib
import logging

log = logging.getLogger(__name__)


def render_to_pdf(template_src, context_dict):

    template = get_template(template_src)
    context = Context(context_dict)
    html = template.render(context)
    result = StringIO()
    pdf = pisa.pisaDocument(StringIO(html.encode("UTF-8")), result, encoding='UTF-8')
    if not pdf.err:
        return http.HttpResponse(result.getvalue(), content_type='application/pdf')
    return http.HttpResponse('We had some errors<pre>%s</pre>' % cgi.escape(html))


def get_basket(request):
    if not request.session.get('basket_id'):
        return
    else:
        try:
            return Basket.objects.get(
                status=BASKET_OPEN, id=request.session.get('basket_id'))
        except Basket.DoesNotExist:
            return


def get_basket_info(request):
    basket = get_basket(request)
    if basket:
        return basket.item_count, basket.summa


def get_or_create_basket(request):
    basket = get_basket(request)
    if not basket:
        basket = Basket.objects.create(session_id=request.session.session_key)
        request.session['basket_id'] = basket.id
    return basket


def create_signature(*args, **kwargs):
    sign_string = '{MNT_ID}{MNT_TRANSACTION_ID}{MNT_AMOUNT}{MNT_CURRENCY_CODE}{MNT_SUBSCRIBER_ID}{MNT_TEST_MODE}{MNT_CHECK_CODE}'.format(**kwargs)
    return hashlib.md5(sign_string).hexdigest()


def make_order_payed(order):
    order.status = ORDER_PAYED
    order.save()

    for order_item in order.items.all():
        order_item.status = ORDER_ITEM_PAYED
        order_item.generate_number()
        if order_item.type == CARD:
            card = Card.create_card(order_item.price)
            order_item.card = card
        order_item.save()

    for transaction in order.transactions.all():
        transaction.status = TRANSACTION_ACCEPTED
        card = transaction.card
        card.blocked = False
        card.save()
        transaction.save()


class AddToBasketView(RedirectView):

    def post(self, request, *args, **kwargs):
        basket = get_or_create_basket(request)
        item = get_object_or_404(Entertainment, id=request.POST.get('cart_item'))

        basket_item, created = BasketItem.objects.get_or_create(basket=basket, item=item)
        if not created:
            basket_item.count += 1
            basket_item.save()

        if basket_item.item.type == PRODUCT and not basket.has_extra_service(DELIVERY):
            BasketExtaItem.objects.create(
                basket=basket,
                type=DELIVERY,
                name='Доставка',
                price=SiteConfiguration.get_solo().price_delivery
            )

        return redirect(request.META['HTTP_REFERER'])

class OrderItemsView(ListView):
    template_name = 'order_items.html'
    model = OrderItem
    context_object_name = 'orderitems_list'

    def filter_queryset(self, qs):
        statuses = self.request.GET.get('status')
        if statuses:
            qs = qs.filter(status__in=list(statuses.split(',')))
        partners = self.request.GET.get('partner')
        if partners:
            qs = qs.filter(partner__in=list(partners.split(',')))
        return qs

    def get_context_data(self, **kwargs):

        context = super(OrderItemsView, self).get_context_data(**kwargs)
        self.queryset = self.filter_queryset(super(OrderItemsView, self).get_queryset())

        price_total = self.queryset.aggregate(Sum('price')).items()[0][1]
        revenue_total = self.queryset.aggregate(Sum('revenue')).items()[0][1]

        context['status'] = ORDER_ITEM_STATUS
        context['partners'] = [(p.id, p.name) for p in Partner.objects.all()]
        context['selected_statuses'] = [int(id) for id in self.request.GET.get('status').split(',')] if self.request.GET.get('status') else None
        context['selected_partners'] = [int(id) for id in self.request.GET.get('partner').split(',')] if self.request.GET.get('partner') else None
        context['price_total'] = price_total if price_total else 0
        context['revenue_total'] = revenue_total if revenue_total else 0
        context['orderitems_list'] = self.queryset
        return context


class EntertainmentView(ListView):

    template_name = 'index.html'
    context_object_name = 'entertainment_list'
    model = Entertainment

    def filter_queryset(self, qs):
        values = self.request.GET.get('tags')
        if values:
            for tag_id in values.split(','):
                try:
                    CategoryItem.objects.get(id=tag_id, active=True)
                    qs = qs.filter(tags__contains=tag_id)
                except CategoryItem.DoesNotExist:
                    pass
        return qs

    def if_filter_active(self, tag_id):
        values = self.request.GET.get('tags')
        if values:
            if tag_id in values:
                return True
        return False

    def get_context_data(self, **kwargs):

        context = super(EntertainmentView, self).get_context_data(**kwargs)
        queryset = super(EntertainmentView, self).get_queryset().filter(active=True)

        queryset = self.filter_queryset(queryset)

        filters = []
        active_filters = []

        for cat_item in CategoryItem.objects.filter(active=True):

            only_check = True
            if cat_item.parent.category_type == CATEGORY_ONLY and self.request.GET.get('tags'):
                for prnt_item in cat_item.parent.items.exclude(id=cat_item.id):
                    if prnt_item.id in self.request.GET.get('tags'):
                        only_check = False

            if only_check:
                item_count = queryset.filter(
                    tags__contains=cat_item.id).count()

                if item_count:
                    if self.if_filter_active(cat_item.id):
                        array = active_filters
                    else:
                        array = filters
                    array.append({
                        'count': item_count,
                        'name': cat_item.name,
                        'id': cat_item.id
                    })

        context['entertainment_list'] = queryset
        context['basket_info'] = get_basket_info(self.request)
        context['filters'] = sorted(
            filters,
            key=lambda key_value: key_value['count'],
            reverse=True
        )
        context['active_filters'] = sorted(
            active_filters,
            key=lambda key_value: key_value['count'],
            reverse=True
        )
        return context


class BasketView(UpdateView):

    model = Basket
    form_class = BasketForm
    second_form_class = OrderCreateForm
    success_url = reverse_lazy('basket')
    success_order_url = reverse_lazy('confirm')

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()

        if 'basket_form' in request.POST:
            form = self.get_form(self.form_class)
            basket_item_form = BasketItemFormSet(request.POST, instance=self.object)

            if form.is_valid() and basket_item_form.is_valid():
                basket_item_form.instance = self.object
                basket_item_form.save()

            context_dict = {
                'basket_form': form,
                'basket_item_form': basket_item_form,
                'card_form': CardForm()
            }

        elif 'order_form' in request.POST:
            form = OrderCreateForm(request.POST)

            if form.is_valid():
                order = form.save(self.request)
                if order.summa_to_pay:
                    return redirect(self.success_order_url)
                else:
                    make_order_payed(order)
                    return HttpResponseRedirect(reverse('payment_success')+'?MNT_TRANSACTION_ID={}'.format(order.id))
            else:
                basket_item_form = BasketItemFormSet(instance=self.get_object())

            context_dict = {
                'basket_form': form,
                'basket_item_form': basket_item_form,
                'card_form': CardForm()
            }

        elif 'card_form' in request.POST:
            form = CardForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                if not Card.objects.filter(login=cd['login'], password=cd['password']):
                    messages.add_message(request, messages.ERROR, u'Карты с такими данными не найдено')
                else:
                    card = Card.objects.get(login=cd['login'], password=cd['password'])
                    if card.blocked:
                        messages.add_message(request, messages.ERROR, u'Карты заблокирована для транзакции')
                    elif card.date_expired < datetime.date.today():

templates/store/basket_form.html
{% extends "base.html" %}
{% load storefilters %}

{% block content %}

{% if object %}

<div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Товар</th>
                    <th>Количество</th>
                    <th class="text-center">Цена</th>
                    <th class="text-center">Сумма</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <form method="post">{% csrf_token %}
                    <fieldset>
                        {{ basket_item_form.management_form }}
                        {% for inline_form in basket_item_form%}
                            {{ inline_form.id }}
                        <tr>
                            <td class="col-sm-8 col-md-6">
                                <div class="media">
                                    <a class="thumbnail pull-left" href="#"><img src="holder.js/100x100"/></a>
                                    <div class="media-body">
                                        <h4 class="media-heading">
                                            {{ inline_form.item.as_hidden }}
                                            {{ inline_form.basket.as_hidden }}
                                            <a href="#">{{ inline_form.instance.item.name }}</a>
                                        </h4>
                                        <span>Характеристики: </span>
                                        <span class="text-success">
                                            <strong>{% for tag in inline_form.instance.item.tag_list %}{{ tag }}&nbsp;{% endfor %}</strong>
                                        </span>
                                    </div>
                                </div>
                            </td>
                            <td class="col-sm-1 col-md-1" style="text-align: center">
                                {{ inline_form.count|addcss:"form-control text-center amount" }}
                            </td>
                            <td class="col-sm-2 col-md-2 text-center"><strong>{{ inline_form.instance.item.price }} руб.</strong></td>
                            <td class="col-sm-2 col-md-2 text-center"><strong>{{ inline_form.instance.item_sum }} руб.</strong></td>
                            <td class="col-sm-1 col-md-1 text-right">
                                <button type="button" class="btn btn-danger remove" data-id="{{ inline_form.instance.id }}" data-type="basket">
                                  <span class="glyphicon glyphicon-remove"></span>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                    </fieldset>

                    <thead>
                        <tr>
                            <th>Подарочные карты</th>
                            <th>&nbsp;</th>
                            <th class="text-center">&nbsp;</th>
                            <th class="text-center">Сумма</th>
                            <th></th>
                        </tr>
                    </thead>
                    {% for transaction in object.transactions.all %}
                        <tr>
                            <td class="col-sm-8 col-md-6">
                                Карта номинал {{ transaction.card.nominal }}
                            </td>
                            <td class="col-sm-1 col-md-1" style="text-align: center">&nbsp;</td>
                            <td class="col-sm-2 col-md-2 text-center">&nbsp;</td>
                            <td class="col-sm-2 col-md-2 text-center">{{ transaction.summa }}</td>
                            <td class="col-sm-1 col-md-1 text-right">
                                <button type="button" class="btn btn-danger remove" data-id="{{ transaction.id }}" data-type="transaction">
                                  <span class="glyphicon glyphicon-remove"></span>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                        <tr>
                            <form method="post">{% csrf_token %}
                            <td class="col-sm-8 col-md-6">
                                <div class="form-group{% if card_form.login.errors %} has-error{% endif %}">
                                    {% for error in card_form.login.errors %}
                                    <label class="control-label" for="id_login">{{ error }}</label>
                                    {% endfor %}
                                    <input class="form-control" id="id_login" maxlength="100" name="login" placeholder="Логин карты" type="text" value="{% if card_form.login.value %}{{ card_form.login.value }}{% endif %}"/>
                                </div>
                            </td>
                            <td colspan="2">
                                <div class="form-group{% if card_form.password.errors %} has-error{% endif %}">
                                    {% for error in card_form.password.errors %}
                                    <label class="control-label" for="id_password">{{ error }}</label>
                                    {% endfor %}
                                    <input class="form-control" id="id_password" maxlength="100" name="password" placeholder="Пароль карты" type="text" value="{% if card_form.password.value %}{{ card_form.password.value }}{% endif %}"/>
                                </div>
                            </td>
                            <td class="text-center">&nbsp;</td>
                            <td class="col-sm-1 col-md-1 text-right">
                                <button type="submit" class="btn btn-success plus" data-id="{{ transaction.id }}" data-type="transaction" name="card_form">
                                  <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </td>
                            </form>
                        </tr>

                    {% if basket_extra_items %}
                        <thead>
                            <tr>
                                <th>Дополнительные услуги</th>
                                <th>&nbsp;</th>
                                <th class="text-center">&nbsp;</th>
                                <th class="text-center">Сумма</th>
                                <th></th>
                            </tr>
                        </thead>
                        {% for item in  basket_extra_items%}
                            <tr>
                                <th>{{ item.name }}</th>
                                <th>&nbsp;</th>
                                <th class="text-center">&nbsp;</th>
                                <th class="text-center">{{ item.price }}</th>
                                <th></th>
                            </tr>
                        {% endfor %}
                    {% endif %}

                    <input type="hidden" name="session_id" value="{{ basket_form.instance.session_id }}"/>
                    <tr>
                        <td>
                            <button type="submit" class="btn btn-primary" id="refresh" name="basket_form">
                                Обновить
                                <span class="glyphicon glyphicon-refresh"></span>
                            </button>
                        </td>
                        <td></td>
                        <td colspan="2"><h3>Итого:</h3></td>
                        <td class="text-right"><h3><strong>{{ object.summa_to_pay }} руб.</strong></h3></td>
                    </tr>
                </form>
                <form method="post" name="order_form">{% csrf_token %}
                    <tr>
                        <td colspan="5">
                            <div class="row">
                                <div class="col-md-3"></div>
                                <div class="col-md-6">
                                    <div class="heading">
                                        <h4 class="form-heading">Ваша контактная информация</h4>
                                    </div>
                                    <p><span class="label label-primary">Внимание:</span> <small> Поля имя и почта являются обязательными.</small></p>
                                    <div class="form-group{% if order_form.username.errors %} has-error{% endif %}">
                                        {% for error in order_form.username.errors %}
                                        <label class="control-label" for="id_username">{{ error }}</label>
                                        {% endfor %}
                                        <input class="form-control" id="id_username" maxlength="100" name="username" placeholder="Имя Фамилия" type="text" value="{% if order_form.username.value %}{{ order_form.username.value }}{% endif %}"/>
                                    </div>
                                    <div class="form-group{% if order_form.email.errors %} has-error{% endif %}">
                                        {% for error in order_form.email.errors %}
                                        <label class="control-label" for="id_email">{{ error }}</label>
                                        {% endfor %}
                                        <input class="form-control" id="id_email" maxlength="100" name="email" placeholder="Электронная почта" type="email" value="{% if order_form.email.value %}{{ order_form.email.value }}{% endif %}"/>
                                    </div>
                                    <div class="form-group{% if order_form.phone.errors %} has-error{% endif %}">
                                        {% for error in order_form.phone.errors %}
                                        <label class="control-label" for="id_phone">{{ error }}</label>
                                        {% endfor %}
                                        <input class="form-control" id="id_phone" maxlength="100" name="phone" placeholder="Телефон" type="text" value="{% if order_form.phone.value %}{{ order_form.phone.value }}{% endif %}"/>
                                    </div>
                                    <div>
                                        <button type="submit" class="btn btn-primary" name="order_form">Оформить</button>
                                    </div>
                                </div>
                                <div class="col-md-3"></div>
                            </div>
                        </td>
                    </tr>
                </form>
                <tr>
                    <td>
                        <a href="/" type="button" class="btn btn-default">
                            <span class="glyphicon glyphicon-arrow-left"></span>
                            Продолжить покупки
                        </a>
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>

{#                        <button type="submit" class="btn btn-primary" id="refresh" name="">#}
{#                            Оплата заказа#}
{#                            <span class="glyphicon glyphicon-arrow-right"></span>#}
{#                        </button>#}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

{% else %}

<div class="row">
	<h3>Корзина пуста</h3>
	<p><a href="/">На главную</a></p>
</div>

{% endif %}

{% endblock %}